#!/bin/bash

echo 'Starting to Deploy...'
ssh ubuntu@52.38.40.75 " sudo docker image prune -f 
        cd PineApple/server/
        export $(cat ~/.env)
        docker-compose down
        git fetch origin
        git reset --hard origin/master  &&  echo 'You are doing well'
        docker-compose build && docker-compose up -d
        "
echo 'Deployment completed successfully'
